name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (to use Docker's build tools)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Render using the Render API Key
      - name: Deploy to Render
        uses: render-examples/render-deploy-action@v1
        with:
          render_api_key: ${{ secrets.RENDER_API_KEY }}
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          docker_image: my-python-app  # The name of your Docker image

